# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ad_image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='read_count',
        ),
        migrations.AddField(
            model_name='course',
            name='course_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='up',
            field=models.BooleanField(default=False, verbose_name='UP'),
        ),
        migrations.AlterField(
            model_name='category',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
